server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Rota especial para o arquivo de configuração
    # É importante que o navegador nunca armazene este arquivo em cache
    location = /env-config.js {
        add_header 'Cache-Control' 'no-cache, no-store, must-revalidate';
        add_header 'Pragma' 'no-cache';
        add_header 'Expires' '0';
    }

    # Rota principal para a SPA (Single Page Application)
    # Redireciona todas as requisições para o index.html para que o React Router funcione
    location / {
        try_files $uri $uri/ /index.html;
    }
}